# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Catalin creciunel
email: catalincreciunel@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Dedicated embedded hardware and software developer with over 3 years 
  of experience in analog and digital circuit development, especially for 
  STM32- and ESP32-based systems. Practice in prototyping, module testing, 
  series production and product maintenance. Knowledge of power electronics, 
  motor control (PID), control engineering and embedded system integration. 
  Experience in ECAD tools such as Altium Designer and KiCad. Interest in modern 
  semiconductor technologies and servo drive systems. German 
  language skills at B1/B2 level, fluent in English.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://creciunel.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

